Upgrade WebDriverManager from 5.3.0 to 5.5.3.
After installing server updates, ItemScreenshotter began crashing:

> org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114

Upgrading fixes this problem. I didn't find a definitive explanation, but there seems to have been some Chrome change that made it so that WebDriverManager itself needed to be updated too.